card_image:
  uploaded_at: 2025-02-06 04:13:41.526000
  url: ''
created_at: 2025-02-06 04:13:41.526000
creator_id: your name
deployment:
  last_deployed: null
  type: null
  url: ''
description: Intro to Memex
domain: Pick one of['Web Development', 'Game Development', 'Mathematics & Visualization']
features:
- ''
getting_started_screen: true
git:
  branch: null
  remote: null
  url: ''
hero_image:
  uploaded_at: 2025-02-06 04:13:41.526000
  url: ''
icon_image:
  uploaded_at: 2025-02-06 14:10:05.618000
  url: https://sample.memexdata.com/icons/getting_started.svg
is_published: false
project_id: 3lCPe84R9wldbbX2QpIm
published_at: null
requirements:
- description: ''
  type: ''
slug: intro-to-memex
storage:
  compression_enabled: null
  gcs_path: null
  last_sync: null
  max_file_size_mb: null
  size_bytes: null
title: Intro to Memex
tools:
- name: ''
  role: ''
  type: ''
  version: ''
updated_at: 2025-02-06 04:13:41.526000
